# Welcome to Jekyll!
title: Pact Coffee for Business
email: business@pactcoffee.com
description: > # this means to ignore newlines until "baseurl:"
port: 4000
host: 127.0.0.1
baseurl: "" # the subpath of your site, e.g. /blog
url: pact-business-varahamihira.netlify.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: 

plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

include:
  - _redirects

permalink: :title
