publish_mode: editorial_workflow
media_folder: "assets/uploads"

backend:
  name: git-gateway
  repo: https://github.com/sites-yari/pact-business
  branch: master # Branch to update (optional; defaults to master)
  site_domain: pact-business-varahamihira.netlify.com

collections:
#====================| POSTS |===================================================|  
  #-----| Read me |------------------------------|
  - name: "blog"
    label: "Blog Posts"
    folder: "_posts/blog"
    create: false
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Public Date", name: "date-shown", widget: "string" }
      - { label: "Visible Link", name: "permalink", widget: "string", default: "/spilling_beans/(name-here)"}
      - { label: "Category", name: "category", widget: "select", options: [ " ", "tasting" , "more to add"] }
      - { label: "Class", name: "class", widget: "hidden", default: "blog" } 
      - { label: "Main Image", name: "image_path", widget: "image" }
      - { label: "Body Text", name: "body", widget: "markdown" }